#
# Cosmological parameters
#
Omega_m : 0.3156
Omega_v : 0.6844
sigma_8 : 0.831
n_spec : 0.9645
w0 : -1.0
wa : 0.0
omb : 0.0492
h0 : 0.6727
coverH0 : 2997.92458
rho_crit : 7.4775e+21
f_NL : 0.0
pdelta_runmode : halofit
#
# Survey and galaxy parameters
#
# area in degrees
# n_gal,lens_n_gal in gals/arcmin^2
area : 2415.0
sourcephotoz : multihisto
lensphotoz : multihisto
source_tomobins : 8
lens_tomobins : 8
sigma_e : 0.39441348451
shear_REDSHIFT_FILE : zdistris/roman_40_8_0.03.nz
clustering_REDSHIFT_FILE : zdistris/roman_40_8_0.03.nz
C_FOOTPRINT_FILE : ini_files/Cl_footprint_DESY3xPlanckPR4_permutation_withAnnulus_4096
HEALPIX_WINDOW_FUNCTION_FILE : ini_files/HPIX1024_pixwin.txt
source_n_gal : 5.1625,5.1625,5.1625,5.1625,5.1625,5.1625,5.1625,5.1625
lens_n_gal : 5.1625,5.1625,5.1625,5.1625,5.1625,5.1625,5.1625,5.1625
lens_tomogbias : 1.4,1.5,1.6,1.7,1.8,1.9,2.0,2.1
#
# Covariance paramters
#
# lmin,lmax
lmin : 30.0
lmax : 4000.0
ncl : 15

nbp : 0
cmbl_nlkk_file : cmblensrec/PlanckPR4_GMV_CMBmarg/NLkk_lmax2048.txt
bindef_file : cmblensrec/PlanckPR4_GMV_CMBmarg/bin_definition.txt
# binmat: only used in k-related covariance (not including kk-kk)
# 
binmat_file : cmblensrec/PlanckPR4_GMV_CMBmarg/binning_matrix.txt
lmin_bp : 8
lmax_bp : 400
# binmat with corr: only used in kk-kk covariance and Ckk dv calculation
#  
binmat_with_corr_file : cmblensrec/PlanckPR4_GMV_CMBmarg/binning_matrix_padded.txt
lmin_bp_with_corr : 2
lmax_bp_with_corr : 2500


ng : 1
#outdir : out_cov_Roman_DC1/
outdir : /xdisk/timeifler/jiachuanxu/RomanPIT/covpara/
filename : Roman_DC1_Fourier_medium
ss : true
ls : true
ll : true
ggl_overlap_cut : 1.0e-20
